name: Publish python dev package
on:
  push:
    branches:
      - develop
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: poetry build
      - name: Semantic Version Release
        uses: python-semantic-release/python-semantic-release@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          root_options: "-vv"
      - name: Publish package distributions to PyPI
        id: release
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}
          root_options: "-vv"
      - name: Test after Publish
        run: |
          pip install -i https://test.pypi.org/simple/ autoload-module
          poetry run pytest
