name: Test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    commitlint:
      name: Lint Commit Messages
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: wagoid/commitlint-github-action@v6
    test:
      strategy:
        matrix:
          python-version: [ "3.9", "3.10", "3.11" ]
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/setup-poetry
          with:
            python-version: ${{ matrix.python-version }}
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: Run Test
          run: python -m unittest -v
